### ISSUE TITLE
Turkish characters are not displayed properly.

### ISSUE THREAD

**Issue by setanarut** [aweekj/kiko-now#1]
Turkish characters are not displayed properly.

**Comment by Tookmund** [comment]
All the characters listed on [wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Turkish_characters) render properly for me with this theme. Is there a specific character you're having trouble with @duurkak ?

**Comment by setanarut** [comment]
> All the characters listed on [wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Turkish_characters) render properly for me with this theme. Is there a specific character you're having trouble with @duurkak ?

It was a year ago. I think it was about utf-8 encoding, I don't remember exactly.
